language: ruby
rvm: 2.5.0
cache: bundler

services:
- mysql
addons:
  ssh_known_hosts: aaronjsutton.com
  apt:
    sources:
      - sourceline: ppa:max-c-lv/shadowsocks-libev
    packages:
      - shadowsocks-libev

before_install:
  - openssl aes-256-cbc -K $encrypted_11f044cd08cf_key -iv $encrypted_11f044cd08cf_iv -in deploy_rsa.enc -out /tmp/deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/deploy_rsa
  - ssh-add /tmp/deploy_rsa
  - sudo apt-get install --no-install-recommends build-essential autoconf libtool libssl-dev libpcre3-dev libev-dev asciidoc xmlto automake
  - git clone https://github.com/shadowsocks/simple-obfs.git
  - cd simple-obfs
  - git submodule update --init --recursive
  - ./autogen.sh
  - ./configure && make
  - sudo make install
  - cd ..

install:
  - bundle install --jobs=3 --retry=3
  - bundle exec rake db:create
  - bundle exec rake db:schema:load

before_script:
  - yardoc

script:
  - brakeman -f html -o /tmp/security.html
  - rubocop -f html -o /tmp/rubocop.html --fail-level E
  - bundle exec rake spec

notifications:
  email:
  - ajsutton.dev@gmail.com

deploy:
  - provider: script
    skip_cleanup: true
    script: bin/reports
    on:
      branch:
        - rewrite
